<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products =[

            [
                'title' => 'Blue Dress For Woman',
                'image' => 'images/product_img1.jpg',
                'price' => 45.00,
                'old_price' => 55.25,
                'discount' => 35,
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                'rating' => 4,
                'rating_count' => 21,
                'colors' => json_encode(["#87554B", "#333333", "#DA323F"]),
                'badge' => null,
                'type' => 'arrival',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Lether Gray Tuxedo',
                'image' => 'images/product_img2.jpg',
                'price' => 55.00,
                'old_price' => 95.00,
                'discount' => 25,
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                'rating' => 3.5,
                'rating_count' => 15,
                'colors' => json_encode(["#847764", "#0393B5", "#DA323F"]),
                'badge' => null,
                'type' => 'arrival',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'woman full sliv dress',
                'image' => 'images/product_img3.jpg',
                'price' => 68.00,
                'old_price' => 99.00,
                'discount' => 31,
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                'rating' => 4.5,
                'rating_count' => 25,
                'colors' => json_encode(["#333333", "#7C502F", "#2F366C", "#874A3D"]),
                'badge' => 'New',
                'type' => 'arrival',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'light blue Shirt',
                'image' => 'images/product_img4.jpg',
                'price' => 69.00,
                'old_price' => 89.00,
                'discount' => 20,
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                'rating' => 3.5,
                'rating_count' => 22,
                'colors' => json_encode(["#333333", "#A92534", "#B9C2DF"]),
                'badge' => null,
                'type' => 'arrival',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'blue dress for woman',
                'image' => 'images/product_img5.jpg',
                'price' => 45.00,
                'old_price' => 55.25,
                'discount' => 35,
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                'rating' => 4,
                'rating_count' => 21,
                'colors' => json_encode(["#87554B", "#333333", "#5FB7D4"]),
                'badge' => null,
                'type' => 'arrival',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Blue casual check shirt',
                'image' => 'images/product_img6.jpg',
                'price' => 55.00,
                'old_price' => 95.00,
                'discount' => 25,
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                'rating' => 3.5,
                'rating_count' => 15,
                'colors' => json_encode(["#87554B", "#333333"]),
                'badge' => 'Hot',
                'type' => 'arrival',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'white black line dress',
                'image' => 'images/product_img7.jpg',
                'price' => 68.00,
                'old_price' => 99.00,
                'discount' => 20,
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                'rating' => 4.5,
                'rating_count' => 25,
                'colors' => json_encode(["#333333", "#7C502F", "#2F366C"]),
                'badge' => 'Sale',
                'type' => 'arrival',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Men blue jins Shirt',
                'image' => 'images/product_img8.jpg',
                'price' => 69.00,
                'old_price' => 89.00,
                'discount' => 20,
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                'rating' => 3.5,
                'rating_count' => 22,
                'colors' => json_encode(["#333333", "#444653", "#B9C2DF"]),
                'badge' => null,
                'type' => 'arrival',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'title' => 'T-Shirt Form Girls',
                'image' => 'images/product_img9.jpg',
                'price' => 45.00,
                'old_price' => 55.25,
                'discount' => 35,
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                'rating' => 4,
                'rating_count' => 21,
                'colors' => json_encode(["#B5B6BB", "#333333", "#DA323F"]),
                'badge' => null,
                'type' => 'bestseller',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Blue casual check shirt',
                'image' => 'images/product_img6.jpg',
                'price' => 55.00,
                'old_price' => 95.00,
                'discount' => 25,
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                'rating' => 3,
                'rating_count' => 15,
                'colors' => json_encode(["#87554B", "#333333"]),
                'badge' => 'Hot',
                'type' => 'bestseller',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Black dress for woman',
                'image' => 'images/product_img11.jpg',
                'price' => 68.00,
                'old_price' => 99.00,
                'discount' => 20,
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                'rating' => 4,
                'rating_count' => 25,
                'colors' => json_encode(["#090909", "#AC644D"]),
                'badge' => null,
                'type' => 'bestseller',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'white black line dress',
                'image' => 'images/product_img7.jpg',
                'price' => 68.00,
                'old_price' => 99.00,
                'discount' => 20,
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                'rating' => 4,
                'rating_count' => 25,
                'colors' => json_encode(["#333333", "#7C502F", "#2F366C"]),
                'badge' => 'Sale',
                'type' => 'bestseller',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Men blue jins Shirt',
                'image' => 'images/product_img8.jpg',
                'price' => 69.00,
                'old_price' => 89.00,
                'discount' => 20,
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                'rating' => 4,
                'rating_count' => 22,
                'colors' => json_encode(["#333333", "#444653", "#B9C2DF"]),
                'badge' => null,
                'type' => 'bestseller',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Blue Dress For Woman',
                'image' => 'images/product_img5.jpg',
                'price' => 45.00,
                'old_price' => 55.25,
                'discount' => 35,
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                'rating' => 4,
                'rating_count' => 21,
                'colors' => json_encode(["#87554B", "#333333", "#5FB7D4"]),
                'badge' => null,
                'type' => 'bestseller',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Black T-shirt for woman',
                'image' => 'images/product_img12.jpg',
                'price' => 69.00,
                'old_price' => 89.00,
                'discount' => 20,
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                'rating' => 4,
                'rating_count' => 22,
                'colors' => json_encode(["#1B1B25", "#444653"]),
                'badge' => 'New',
                'type' => 'bestseller',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Red & Black check shirt',
                'image' => 'images/product_img10.jpg',
                'price' => 55.00,
                'old_price' => 95.00,
                'discount' => 25,
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                'rating' => 3,
                'rating_count' => 15,
                'colors' => json_encode(["#E8ADA9", "#C38F77", "#BE7154"]),
                'badge' => 'Hot',
                'type' => 'bestseller',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],


            [
                'title' => 'Blue Dress For Woman',
                'image' => 'images/product_img5.jpg',
                'price' => 45.00,
                'old_price' => 55.25,
                'discount' => 35,
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                'rating' => 4,
                'rating_count' => 21,
                'colors' => json_encode(["#87554B", "#333333", "#5FB7D4"]),
                'badge' => null,
                'type' => 'featured',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Black T-shirt for woman',
                'image' => 'images/product_img12.jpg',
                'price' => 69.00,
                'old_price' => 89.00,
                'discount' => 20,
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                'rating' => 3.5,
                'rating_count' => 22,
                'colors' => json_encode(["#1B1B25", "#444653"]),
                'badge' => 'New',
                'type' => 'featured',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'T-Shirt Form Girls',
                'image' => 'images/product_img9.jpg',
                'price' => 45.00,
                'old_price' => 55.25,
                'discount' => 35,
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                'rating' => 4,
                'rating_count' => 21,
                'colors' => json_encode(["#B5B6BB", "#333333", "#DA323F"]),
                'badge' => null,
                'type' => 'featured',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Red & Black check shirt',
                'image' => 'images/product_img10.jpg',
                'price' => 55.00,
                'old_price' => 95.00,
                'discount' => 25,
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                'rating' => 3.5,
                'rating_count' => 15,
                'colors' => json_encode(["#E8ADA9", "#C38F77", "#BE7154"]),
                'badge' => 'Sale',
                'type' => 'featured',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'white black line dress',
                'image' => 'images/product_img7.jpg',
                'price' => 68.00,
                'old_price' => 99.00,
                'discount' => 20,
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                'rating' => 4.5,
                'rating_count' => 25,
                'colors' => json_encode(["#333333", "#7C502F", "#2F366C"]),
                'badge' => 'Hot',
                'type' => 'featured',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Black dress for woman',
                'image' => 'images/product_img11.jpg',
                'price' => 68.00,
                'old_price' => 99.00,
                'discount' => 20,
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                'rating' => 4.5,
                'rating_count' => 25,
                'colors' => json_encode(["#090909", "#AC644D"]),
                'badge' => null,
                'type' => 'featured',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Men blue jins Shirt',
                'image' => 'images/product_img8.jpg',
                'price' => 69.00,
                'old_price' => 89.00,
                'discount' => 20,
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                'rating' => 3.5,
                'rating_count' => 22,
                'colors' => json_encode(["#333333", "#444653", "#B9C2DF"]),
                'badge' => null,
                'type' => 'featured',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Blue casual check shirt',
                'image' => 'images/product_img6.jpg',
                'price' => 55.00,
                'old_price' => 95.00,
                'discount' => 25,
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                'rating' => 3.5,
                'rating_count' => 15,
                'colors' => json_encode(["#87554B", "#333333"]),
                'badge' => 'Sale',
                'type' => 'featured',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'title' => 'light blue Shirt',
                'image' => 'images/product_img4.jpg',
                'price' => 69.00,
                'old_price' => 89.00,
                'discount' => 20,
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                'rating' => 3.5,
                'rating_count' => 22,
                'colors' => json_encode(["#333333", "#A92534", "#B9C2DF"]),
                'badge' => null,
                'type' => 'special',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'T-Shirt Form Girls',
                'image' => 'images/product_img9.jpg',
                'price' => 45.00,
                'old_price' => 55.25,
                'discount' => 35,
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                'rating' => 4,
                'rating_count' => 21,
                'colors' => json_encode(["#B5B6BB", "#333333", "#DA323F"]),
                'badge' => null,
                'type' => 'special',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Men Checks Casual Shirt',
                'image' => 'images/product_img8.jpg',
                'price' => 69.00,
                'old_price' => 89.00,
                'discount' => 20,
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                'rating' => 3.5,
                'rating_count' => 22,
                'colors' => json_encode(["#333333", "#444653", "#B9C2DF"]),
                'badge' => null,
                'type' => 'special',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Blue Dress For Woman',
                'image' => 'images/product_img1.jpg',
                'price' => 45.00,
                'old_price' => 55.25,
                'discount' => 35,
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                'rating' => 4,
                'rating_count' => 21,
                'colors' => json_encode(["#87554B", "#333333", "#DA323F"]),
                'badge' => 'New',
                'type' => 'special',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Black T-shirt for woman',
                'image' => 'images/product_img12.jpg',
                'price' => 69.00,
                'old_price' => 89.00,
                'discount' => 20,
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                'rating' => 3.5,
                'rating_count' => 22,
                'colors' => json_encode(["#1B1B25", "#444653"]),
                'badge' => 'Hot',
                'type' => 'special',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Blue casual check shirt',
                'image' => 'images/product_img6.jpg',
                'price' => 55.00,
                'old_price' => 95.00,
                'discount' => 25,
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                'rating' => 3.5,
                'rating_count' => 15,
                'colors' => json_encode(["#87554B", "#333333"]),
                'badge' => null,
                'type' => 'special',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'white black line dress',
                'image' => 'images/product_img7.jpg',
                'price' => 68.00,
                'old_price' => 99.00,
                'discount' => 20,
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                'rating' => 4.5,
                'rating_count' => 25,
                'colors' => json_encode(["#333333", "#7C502F", "#2F366C"]),
                'badge' => 'Sale',
                'type' => 'special',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Black dress for woman',
                'image' => 'images/product_img11.jpg',
                'price' => 68.00,
                'old_price' => 99.00,
                'discount' => 20,
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                'rating' => 4.5,
                'rating_count' => 25,
                'colors' => json_encode(["#090909", "#AC644D"]),
                'badge' => null,
                'type' => 'special',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        $existingSlugs = [];
        $finalProducts = [];

        foreach ($products as $product) {
            $baseSlug = Str::slug($product['title']) . '-' . $product['type'];
            $slug = $this->generateUniqueSlug($baseSlug, $existingSlugs);

            $finalProducts[] = [
                'title' => $product['title'],
                'slug' => $slug,
                'image' => $product['image'],
                'price' => $product['price'],
                'old_price' => $product['old_price'],
                'discount' => $product['discount'],
                'description' => $product['description'],
                'rating' => $product['rating'],
                'rating_count' => $product['rating_count'],
                'colors' => json_encode($product['colors']),
                'badge' => $product['badge'],
                'type' => $product['type'],
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ];
        }

        DB::table('products')->insert($finalProducts);
    }

    private function generateUniqueSlug($baseSlug, &$existingSlugs)
    {
        $slug = $baseSlug;
        $i = 1;

        while (in_array($slug, $existingSlugs)) {
            $slug = $baseSlug . '-' . $i;
            $i++;
        }

        $existingSlugs[] = $slug;

        return $slug;
    }
}
